# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:29
from __future__ import unicode_literals

import b24online.custom
import b24online.models
import b24online.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('b24online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSiteTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_bg', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('folder_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_ru', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_am', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_bg', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_en', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_uk', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_he', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_ar', models.CharField(blank=True, max_length=2048, null=True)),
                ('slogan_zh', models.CharField(blank=True, max_length=2048, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('logo', b24online.custom.CustomImageField(max_length=255, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('footer_text_ru', models.TextField(blank=True, null=True)),
                ('footer_text_am', models.TextField(blank=True, null=True)),
                ('footer_text_bg', models.TextField(blank=True, null=True)),
                ('footer_text_en', models.TextField(blank=True, null=True)),
                ('footer_text_uk', models.TextField(blank=True, null=True)),
                ('footer_text_he', models.TextField(blank=True, null=True)),
                ('footer_text_ar', models.TextField(blank=True, null=True)),
                ('footer_text_zh', models.TextField(blank=True, null=True)),
                ('domain_part', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersite_create_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b24online.Organization')),
                ('site', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_site', to='sites.Site')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersites.ExternalSiteTemplate')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersite_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.CreateModel(
            name='UserSiteTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('thumbnail', b24online.custom.CustomImageField(max_length=255, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path)),
                ('folder_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='usersite',
            name='user_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersites.UserSiteTemplate'),
        ),
    ]
