# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0002_auto_20160218_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('ru', 'Russian'), ('am', 'Armenian'), ('bg', 'Bulgarian'), ('en', 'English'), ('uk', 'Ukrainian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese')], default='auto', max_length=4),
        ),
    ]
