# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 16:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0003_usersite_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
