# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0005_auto_20160519_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
