# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0006_auto_20160530_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsitetemplate',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersite',
            name='footer_text_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersite',
            name='slogan_es',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('ru', 'Russian'), ('am', 'Armenian'), ('bg', 'Bulgarian'), ('en', 'English'), ('uk', 'Ukrainian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('es', 'Spanish')], default='auto', max_length=4),
        ),
    ]
