# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0007_auto_20160622_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersite',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='usersite',
            name='delivery_currency',
            field=models.CharField(choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersite',
            name='is_delivery_available',
            field=models.BooleanField(default=True),
        ),
    ]
