# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0008_auto_20160716_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='language',
            field=models.CharField(choices=[('auto', 'Auto'), ('en', 'English'), ('ru', 'Russian'), ('am', 'Armenian'), ('bg', 'Bulgarian'), ('uk', 'Ukrainian'), ('he', 'Hebrew'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('es', 'Spanish')], default='auto', max_length=4),
        ),
    ]
