# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0009_auto_20161002_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_user_site', to='b24online.Organization'),
        ),
    ]
