# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:53
from __future__ import unicode_literals

import b24online.custom
import b24online.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0010_auto_20161022_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSiteSchemeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('folder_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Scheme colors',
                'verbose_name': 'Scheme color',
            },
        ),
        migrations.AlterModelOptions(
            name='usersitetemplate',
            options={'verbose_name': 'Tempate', 'verbose_name_plural': 'Tempates'},
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersitetemplate',
            name='thumbnail',
            field=b24online.custom.CustomImageField(max_length=1000, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path),
        ),
        migrations.AddField(
            model_name='usersiteschemecolor',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='usersites.UserSiteTemplate'),
        ),
        migrations.AddField(
            model_name='usersite',
            name='color_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usersites.UserSiteSchemeColor'),
        ),
    ]
