# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0011_auto_20161119_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_bg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_he',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_uk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersitetemplate',
            name='description_zh',
            field=models.TextField(blank=True, null=True),
        ),
    ]
