# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0014_usersite_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersitetemplate',
            name='typeof',
            field=models.IntegerField(choices=[(0, 'Simple'), (1, 'Extend')], default=0),
        ),
    ]
