# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:42
from __future__ import unicode_literals

import b24online.custom
import b24online.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersites', '0015_usersitetemplate_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', b24online.custom.CustomImageField(max_length=255, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landingpage_create_user', to=settings.AUTH_USER_MODEL)),
                ('src', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='usersites.UserSite')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landingpage_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
