# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0017_auto_20170321_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landingpage',
            old_name='image',
            new_name='cover',
        ),
    ]
