# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersites', '0019_auto_20170321_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersite',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='usersite',
            name='delivery_currency',
            field=models.CharField(blank=True, choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')], max_length=20, null=True),
        ),
    ]
