version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nx01
    command: nginx
    ports:
      - "8000:80"
      - "443:443"
      - "9999:9999"
    volumes:
      - ./static-assets:/src/static-assets
      - ./static:/src/static
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx-app.conf:/etc/nginx/conf.d/b24.conf
      - ./log/nginx:/var/log/nginx
      - ./letsencrypt:/src/letsencrypt
    depends_on:
      - web
  web:
    environment:
      - NEW_RELIC_CONFIG_FILE=/src/newrelic.ini
    build: .
    container_name: dg01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/gunicorn -b 0.0.0.0:8001 tpp.b24online_wsgi'
    volumes:
      - ./static-assets:/src/static-assets
      - ./b24project:/src/b24project
      - ./templates:/src/templates
      - ./locale:/src/locale
      - ./static:/src/static
      - ./uploads:/src/uploads
      - ./settings_docker.py:/src/b24project/local_settings.py
      - ./newrelic.ini:/src/newrelic.ini
    expose:
      - "8001"
      - "443:443"
    restart: always

  celery:
    build: .
    environment:
      - NEW_RELIC_CONFIG_FILE=/src/newrelic.ini
    container_name: cl01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/newrelic-admin run-program /usr/local/bin/celery worker -A tpp'
    volumes:
      - ./b24project:/src/b24project
      - ./uploads:/src/uploads
      - ./settings_docker.py:/src/b24project/local_settings.py
      - ./newrelic_celery.ini:/src/newrelic.ini
    restart: always

  beat:
    build: .
    environment:
      - NEW_RELIC_CONFIG_FILE=/src/newrelic.ini
    container_name: cb01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/newrelic-admin run-program /usr/local/bin/celery beat -A tpp --pidfile /tmp/celerybeat.pid'
    volumes:
      - ./b24project:/src/b24project
      - ./settings_docker.py:/src/b24project/local_settings.py
      - ./newrelic_celery.ini:/src/newrelic.ini
    restart: always

  tornado:
    build: .
    environment:
      - NEW_RELIC_CONFIG_FILE=/src/newrelic.ini
    container_name: tr01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/newrelic-admin run-program python3 manage.py async_server'
    volumes:
      - ./b24project:/src/b24project
      - ./settings_docker.py:/src/b24project/local_settings.py
      - ./newrelic_tornado.ini:/src/newrelic.ini
    ports:
      - "9999:9999"
    restart: always