version: '2'
services:
  nginx:
    image: nginx
    container_name: nx01
    command: nginx
    ports:
      - "80:80"
    volumes:
      - ./static-assets:/src/static-assets
      - ./static:/src/static
      - ./.docker/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx-app.local.conf:/etc/nginx/conf.d/b24.conf
      - ./log/nginx:/var/log/nginx
    depends_on:
      - web
      - usersite
      - tornado
    restart: always

  db:
    image: postgres:9.5
    hostname: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    hostname: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
    restart: always

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./redis/data:/data


  web:
    environment:
      - DJANGO_SETTINGS_MODULE=tpp.settings
      - SETTING_DB_NAME=postgres
      - SETTING_DB_USER=postgres
      - SETTING_DB_PASSWORD=postgres
      - SETTING_DB_HOST=db
      - SETTING_BUCKET=tppuploads
    build: .
    container_name: dg01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/gunicorn -b 0.0.0.0:8001 --log-file /src/log/gunicorn.log --log-level debug tpp.wsgi'
    volumes:
      - ./b24project/local_settings.py:/src/b24project/local_settings.py
      - ./log/web/:/src/log/
      - ./static-assets:/src/static-assets
      - ./b24project:/src/b24project
      - ./templates:/src/templates
      - ./locale:/src/locale
      - ./static:/src/static
      - ./uploads:/src/uploads
      - ./install.sh:/src/b24project/install.sh
      - ./fixtures:/src/fixtures
      - ./geoip/GeoLite2-City.mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
      - ./geoip/GeoLite2-Country.mmdb:/usr/share/GeoIP/GeoLite2-Country.mmdb
    depends_on:
      - redis
      - elasticsearch
      - db
    expose:
      - "8001"
    restart: always

  usersite:
    environment:
      - DJANGO_SETTINGS_MODULE=tpp.usersites_settings
      - SETTING_DB_NAME=postgres
      - SETTING_DB_USER=postgres
      - SETTING_DB_PASSWORD=postgres
      - SETTING_DB_HOST=db
      - SETTING_BUCKET=tppuploads
    build: .
    container_name: dg02
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/gunicorn -b 0.0.0.0:8002 -w 5 -t 300 --log-file /src/log/gunicorn.log --log-level debug tpp.wsgi'
    volumes:
      - ./b24project/local_settings.py:/src/b24project/local_settings.py
      - ./log/usersite/:/src/log/
      - ./static-assets:/src/static-assets
      - ./b24project:/src/b24project
      - ./templates:/src/templates
      - ./locale:/src/locale
      - ./static:/src/static
      - ./uploads:/src/uploads
      - ./geoip/GeoLite2-City.mmdb:/usr/share/GeoIP/GeoLite2-City.mmdb
      - ./geoip/GeoLite2-Country.mmdb:/usr/share/GeoIP/GeoLite2-Country.mmdb
    depends_on:
      - redis
      - elasticsearch
      - db
    expose:
      - "8002"
    restart: always

  celery:
    build: .
    environment:
      - SETTING_DB_NAME=postgres
      - SETTING_DB_USER=postgres
      - SETTING_DB_PASSWORD=postgres
      - SETTING_DB_HOST=db
      - SETTING_BUCKET=tppuploads
    container_name: cl01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/celery worker -A tpp -f /src/log/celery.log -l DEBUG'
    volumes:
      - ./b24project/local_settings.py:/src/b24project/local_settings.py
      - ./log/celery/:/src/log/
      - ./b24project:/src/b24project
      - ./uploads:/src/uploads
    depends_on:
      - redis
      - elasticsearch
      - db
    restart: always

  beat:
    build: .
    environment:
      - SETTING_DB_NAME=postgres
      - SETTING_DB_USER=postgres
      - SETTING_DB_PASSWORD=postgres
      - SETTING_DB_HOST=db
      - SETTING_BUCKET=tppuploads
    container_name: cb01
    working_dir: /src/b24project
    command: bash -c '/usr/local/bin/celery beat -A tpp --pidfile /tmp/beat/celerybeat.pid -f /src/log/celery.log -l DEBUG'
    volumes:
      - ./b24project/local_settings.py:/src/b24project/local_settings.py
      - ./:/tmp/beat/
      - ./log/beat/:/src/log/
      - ./b24project:/src/b24project
    depends_on:
      - redis
      - elasticsearch
      - db
    restart: always

  tornado:
    build: .
    environment:
      - SETTING_DB_NAME=postgres
      - SETTING_DB_USER=postgres
      - SETTING_DB_PASSWORD=postgres
      - SETTING_DB_HOST=db
      - SETTING_BUCKET=tppuploads
    container_name: tr01
    working_dir: /src/b24project
    command: bash -c 'python3 manage.py async_server'
    volumes:
      - ./b24project/local_settings.py:/src/b24project/local_settings.py
      - ./log/tornado/:/src/log/
      - ./b24project:/src/b24project
    expose:
      - "9998"
    depends_on:
      - redis
      - elasticsearch
      - db
    restart: always