# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 17:29
from __future__ import unicode_literals

import b24online.custom
import b24online.models
import b24online.utils
from django.conf import settings
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b24online', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2CProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_bg', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_bg', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('short_description', models.TextField()),
                ('short_description_ru', models.TextField(null=True)),
                ('short_description_am', models.TextField(null=True)),
                ('short_description_bg', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_uk', models.TextField(null=True)),
                ('short_description_he', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('short_description_zh', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('image', b24online.custom.CustomImageField(blank=True, max_length=255, null=True, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path)),
                ('keywords', models.CharField(blank=True, max_length=2048)),
                ('keywords_ru', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_am', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_bg', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_en', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_uk', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_he', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_ar', models.CharField(blank=True, max_length=2048, null=True)),
                ('keywords_zh', models.CharField(blank=True, max_length=2048, null=True)),
                ('currency', models.CharField(choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')], max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('discount_percent', models.FloatField(blank=True, null=True)),
                ('coupon_discount_percent', models.FloatField(blank=True, null=True)),
                ('coupon_dates', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='B2CProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_bg', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_bg', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('image', b24online.custom.CustomImageField(blank=True, null=True, storage=b24online.custom.S3ImageStorage(), upload_to='')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='centerpokupok.B2CProductCategory')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='B2CProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2cproductcomment_create_user', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='centerpokupok.B2CProductComment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerpokupok.B2CProduct')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2cproductcomment_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
            ],
            options={
                'ordering': ('basket',),
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='UserBasket',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_id', models.IntegerField(default=143, verbose_name='Site ID')),
                ('currency', models.CharField(blank=True, max_length=11, null=True)),
                ('paypal', models.CharField(blank=True, max_length=111, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('checked_out', models.BooleanField(default=False, verbose_name='Ordered?')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name': 'Basket',
                'verbose_name_plural': 'Baskets',
            },
        ),
        migrations.AddField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='centerpokupok.UserBasket', verbose_name='basket'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_product', to='centerpokupok.B2CProduct'),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='centerpokupok.B2CProductCategory'),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_products', to='b24online.Company'),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2cproduct_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2cproduct_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='b2cproduct',
            index_together=set([('created_at', 'company')]),
        ),
    ]
