# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0005_auto_20160229_0748'),
        ('centerpokupok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cproduct',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_products', to='b24online.Producer', verbose_name='Producer'),
        ),
    ]
