# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0002_b2cproduct_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cproduct',
            name='extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extra param fields'),
        ),
    ]
