# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0003_b2cproduct_extra_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extra parameters values'),
        ),
    ]
