# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0004_basketitem_extra_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cproduct',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='keywords_es',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='short_description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='b2cproduct',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b2cproductcategory',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='b2cproductcategory',
            name='slug_es',
            field=models.SlugField(max_length=255, null=True),
        ),
    ]
