# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 16:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0005_auto_20160622_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cproduct',
            name='additional_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), size=None), blank=True, null=True, size=None),
        ),
    ]
