# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0006_b2cproduct_additional_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cproduct',
            name='show_on_main',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
