# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0007_b2cproduct_show_on_main'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='b2cproductcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='b2cproductcomment',
            managers=[
            ],
        ),
    ]
