# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0008_auto_20161002_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2cproduct',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='b2cproduct',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
