# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0009_auto_20161016_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ('basket',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='userbasket',
            options={'ordering': ('-created',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AlterField(
            model_name='b2cproduct',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_products', to='b24online.Producer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='centerpokupok.UserBasket', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='userbasket',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='userbasket',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Созданно'),
        ),
        migrations.AlterField(
            model_name='userbasket',
            name='site_id',
            field=models.IntegerField(default=143, verbose_name='Сайт'),
        ),
    ]
