# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0010_auto_20161119_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('centerpokupok.b2cproduct',),
        ),
    ]
