# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0011_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbasket',
            name='site_id',
            field=models.IntegerField(default=1, verbose_name='Сайт'),
        ),
    ]
