# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0012_auto_20170321_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketitem',
            options={'ordering': ('basket',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='userbasket',
            options={'ordering': ('-created',), 'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterField(
            model_name='b2cproduct',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2c_products', to='b24online.Producer', verbose_name='Producer'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='centerpokupok.UserBasket', verbose_name='basket'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='userbasket',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='Ordered?'),
        ),
        migrations.AlterField(
            model_name='userbasket',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='userbasket',
            name='site_id',
            field=models.IntegerField(default=1, verbose_name='Site ID'),
        ),
    ]
