# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-25 10:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centerpokupok', '0013_auto_20170417_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2cproduct',
            name='colors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Colors'), blank=True, null=True, size=None),
        ),
    ]
