from appl.models import (Advertising, Announce, Article, Basket, Company, Cabinet, Department, Document,
                         Invoice, News, Forum, ForumPost, ForumThread, Order, Payment, Product, Tpp, Tender,
                         Rate, Rating, Review, Service, Site, Shipment, Gallery)

from django.contrib import admin

admin.site.register(Advertising)
admin.site.register(Announce)
admin.site.register(Article)
admin.site.register(Basket)
admin.site.register(Company)
admin.site.register(Cabinet)
admin.site.register(Department)
admin.site.register(Document)
admin.site.register(Invoice)
admin.site.register(News)
admin.site.register(Forum)
admin.site.register(ForumPost)
admin.site.register(ForumThread)
admin.site.register(Order)
admin.site.register(Payment)
admin.site.register(Product)
admin.site.register(Tpp)
admin.site.register(Tender)
admin.site.register(Rate)
admin.site.register(Rating)
admin.site.register(Review)
admin.site.register(Service)
admin.site.register(Site)
admin.site.register(Shipment)
admin.site.register(Gallery)
