# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.contrib.postgres.fields.ranges
import polymorphic_tree.models
import b24online.utils
import b24online.models
import b24online.custom
import django.contrib.postgres.fields.hstore
import django.utils.timezone
from django.conf import settings
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0006_require_contenttypes_0002'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPage',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(null=True, max_length=255)),
                ('title_am', models.CharField(null=True, max_length=255)),
                ('title_bg', models.CharField(null=True, max_length=255)),
                ('title_en', models.CharField(null=True, max_length=255)),
                ('title_uk', models.CharField(null=True, max_length=255)),
                ('title_he', models.CharField(null=True, max_length=255)),
                ('title_ar', models.CharField(null=True, max_length=255)),
                ('title_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_bg', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(related_name='additionalpage_create_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(related_name='additionalpage_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('advertisement_type', models.CharField(max_length=10, choices=[('banner', 'Banners'), ('context', 'Context Advertisement')])),
                ('object_id', models.PositiveIntegerField()),
                ('dates', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('price', models.DecimalField(max_digits=15, decimal_places=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(related_name='advertisementprice_create_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(related_name='advertisementprice_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='B2BProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('name_ru', models.CharField(null=True, max_length=2048)),
                ('name_am', models.CharField(null=True, max_length=2048)),
                ('name_bg', models.CharField(null=True, max_length=2048)),
                ('name_en', models.CharField(null=True, max_length=2048)),
                ('name_uk', models.CharField(null=True, max_length=2048)),
                ('name_he', models.CharField(null=True, max_length=2048)),
                ('name_ar', models.CharField(null=True, max_length=2048)),
                ('name_zh', models.CharField(null=True, max_length=2048)),
                ('slug', models.SlugField(max_length=2048)),
                ('slug_ru', models.SlugField(null=True, max_length=2048)),
                ('slug_am', models.SlugField(null=True, max_length=2048)),
                ('slug_bg', models.SlugField(null=True, max_length=2048)),
                ('slug_en', models.SlugField(null=True, max_length=2048)),
                ('slug_uk', models.SlugField(null=True, max_length=2048)),
                ('slug_he', models.SlugField(null=True, max_length=2048)),
                ('slug_ar', models.SlugField(null=True, max_length=2048)),
                ('slug_zh', models.SlugField(null=True, max_length=2048)),
                ('short_description', models.TextField()),
                ('short_description_ru', models.TextField(null=True)),
                ('short_description_am', models.TextField(null=True)),
                ('short_description_bg', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_uk', models.TextField(null=True)),
                ('short_description_he', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('short_description_zh', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('image', b24online.custom.CustomImageField(null=True, upload_to=b24online.utils.generate_upload_path, storage=b24online.custom.S3ImageStorage(), max_length=255, blank=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('currency', models.CharField(null=True, choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')], max_length=255, blank=True)),
                ('measurement_unit', models.CharField(null=True, choices=[('kg', 'Kilogram'), ('pcs', 'Piece')], max_length=255, blank=True)),
                ('cost', models.DecimalField(max_digits=15, null=True, decimal_places=2, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='B2BProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('image', b24online.custom.CustomImageField(null=True, upload_to='', storage=b24online.custom.S3ImageStorage(), blank=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, related_name='children', blank=True, to='b24online.B2BProductCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='B2BProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(related_name='b2bproductcomment_create_user', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(null=True, related_name='children', blank=True, to='b24online.B2BProductComment')),
                ('product', models.ForeignKey(to='b24online.B2BProduct')),
                ('updated_by', models.ForeignKey(related_name='b2bproductcomment_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('width', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('height', models.PositiveSmallIntegerField(null=True, blank=True)),
                ('image', b24online.custom.CustomImageField(null=True, upload_to='', storage=b24online.custom.S3ImageStorage(), blank=True)),
                ('description', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_ru', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_am', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_bg', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_en', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_uk', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_he', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_ar', models.CharField(null=True, max_length=1024, blank=True)),
                ('description_zh', models.CharField(null=True, max_length=1024, blank=True)),
                ('factor', models.FloatField(default=1)),
                ('block_type', models.CharField(max_length=10, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('user_site', 'User sites')])),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, related_name='children', blank=True, to='b24online.Branch')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='BusinessProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(null=True, max_length=255)),
                ('title_am', models.CharField(null=True, max_length=255)),
                ('title_bg', models.CharField(null=True, max_length=255)),
                ('title_en', models.CharField(null=True, max_length=255)),
                ('title_uk', models.CharField(null=True, max_length=255)),
                ('title_he', models.CharField(null=True, max_length=255)),
                ('title_ar', models.CharField(null=True, max_length=255)),
                ('title_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='BusinessProposalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, related_name='children', blank=True, to='b24online.BusinessProposalCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('flag', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
            ],
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(related_name='department_create_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(null=True, max_length=255)),
                ('description_am', models.CharField(null=True, max_length=255)),
                ('description_bg', models.CharField(null=True, max_length=255)),
                ('description_en', models.CharField(null=True, max_length=255)),
                ('description_uk', models.CharField(null=True, max_length=255)),
                ('description_he', models.CharField(null=True, max_length=255)),
                ('description_ar', models.CharField(null=True, max_length=255)),
                ('description_zh', models.CharField(null=True, max_length=255)),
                ('document', models.FileField(upload_to=b24online.utils.document_upload_path)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(related_name='document_create_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(related_name='document_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(null=True, max_length=255)),
                ('title_am', models.CharField(null=True, max_length=255)),
                ('title_bg', models.CharField(null=True, max_length=255)),
                ('title_en', models.CharField(null=True, max_length=255)),
                ('title_uk', models.CharField(null=True, max_length=255)),
                ('title_he', models.CharField(null=True, max_length=255)),
                ('title_ar', models.CharField(null=True, max_length=255)),
                ('title_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('city', models.CharField(null=True, max_length=255)),
                ('city_ru', models.CharField(null=True, max_length=255)),
                ('city_am', models.CharField(null=True, max_length=255)),
                ('city_bg', models.CharField(null=True, max_length=255)),
                ('city_en', models.CharField(null=True, max_length=255)),
                ('city_uk', models.CharField(null=True, max_length=255)),
                ('city_he', models.CharField(null=True, max_length=255)),
                ('city_ar', models.CharField(null=True, max_length=255)),
                ('city_zh', models.CharField(null=True, max_length=255)),
                ('route', models.CharField(max_length=2048, blank=True)),
                ('route_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('route_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
                ('country', models.ForeignKey(to='b24online.Country')),
                ('created_by', models.ForeignKey(related_name='exhibition_create_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(null=True, max_length=266)),
                ('title_ru', models.CharField(null=True, max_length=266)),
                ('title_am', models.CharField(null=True, max_length=266)),
                ('title_bg', models.CharField(null=True, max_length=266)),
                ('title_en', models.CharField(null=True, max_length=266)),
                ('title_uk', models.CharField(null=True, max_length=266)),
                ('title_he', models.CharField(null=True, max_length=266)),
                ('title_ar', models.CharField(null=True, max_length=266)),
                ('title_zh', models.CharField(null=True, max_length=266)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(related_name='gallery_create_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(related_name='gallery_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('image', b24online.custom.CustomImageField(storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(related_name='galleryimage_create_user', to=settings.AUTH_USER_MODEL)),
                ('gallery', models.ForeignKey(related_name='gallery_items', to='b24online.Gallery')),
                ('updated_by', models.ForeignKey(related_name='galleryimage_update_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('photo', b24online.custom.CustomImageField(storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_name_ru', models.CharField(null=True, max_length=255)),
                ('organization_name_am', models.CharField(null=True, max_length=255)),
                ('organization_name_bg', models.CharField(null=True, max_length=255)),
                ('organization_name_en', models.CharField(null=True, max_length=255)),
                ('organization_name_uk', models.CharField(null=True, max_length=255)),
                ('organization_name_he', models.CharField(null=True, max_length=255)),
                ('organization_name_ar', models.CharField(null=True, max_length=255)),
                ('organization_name_zh', models.CharField(null=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('position_name_ru', models.CharField(null=True, max_length=255)),
                ('position_name_am', models.CharField(null=True, max_length=255)),
                ('position_name_bg', models.CharField(null=True, max_length=255)),
                ('position_name_en', models.CharField(null=True, max_length=255)),
                ('position_name_uk', models.CharField(null=True, max_length=255)),
                ('position_name_he', models.CharField(null=True, max_length=255)),
                ('position_name_ar', models.CharField(null=True, max_length=255)),
                ('position_name_zh', models.CharField(null=True, max_length=255)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_bg', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
            ],
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='InnovationProject',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('name_ru', models.CharField(null=True, max_length=2048)),
                ('name_am', models.CharField(null=True, max_length=2048)),
                ('name_bg', models.CharField(null=True, max_length=2048)),
                ('name_en', models.CharField(null=True, max_length=2048)),
                ('name_uk', models.CharField(null=True, max_length=2048)),
                ('name_he', models.CharField(null=True, max_length=2048)),
                ('name_ar', models.CharField(null=True, max_length=2048)),
                ('name_zh', models.CharField(null=True, max_length=2048)),
                ('slug', models.SlugField(max_length=2048)),
                ('slug_ru', models.SlugField(null=True, max_length=2048)),
                ('slug_am', models.SlugField(null=True, max_length=2048)),
                ('slug_bg', models.SlugField(null=True, max_length=2048)),
                ('slug_en', models.SlugField(null=True, max_length=2048)),
                ('slug_uk', models.SlugField(null=True, max_length=2048)),
                ('slug_he', models.SlugField(null=True, max_length=2048)),
                ('slug_ar', models.SlugField(null=True, max_length=2048)),
                ('slug_zh', models.SlugField(null=True, max_length=2048)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('product_name', models.CharField(max_length=2048)),
                ('product_name_ru', models.CharField(null=True, max_length=2048)),
                ('product_name_am', models.CharField(null=True, max_length=2048)),
                ('product_name_bg', models.CharField(null=True, max_length=2048)),
                ('product_name_en', models.CharField(null=True, max_length=2048)),
                ('product_name_uk', models.CharField(null=True, max_length=2048)),
                ('product_name_he', models.CharField(null=True, max_length=2048)),
                ('product_name_ar', models.CharField(null=True, max_length=2048)),
                ('product_name_zh', models.CharField(null=True, max_length=2048)),
                ('business_plan', models.TextField()),
                ('business_plan_ru', models.TextField(null=True)),
                ('business_plan_am', models.TextField(null=True)),
                ('business_plan_bg', models.TextField(null=True)),
                ('business_plan_en', models.TextField(null=True)),
                ('business_plan_uk', models.TextField(null=True)),
                ('business_plan_he', models.TextField(null=True)),
                ('business_plan_ar', models.TextField(null=True)),
                ('business_plan_zh', models.TextField(null=True)),
                ('currency', models.CharField(null=True, max_length=255, choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')])),
                ('cost', models.DecimalField(max_digits=15, null=True, decimal_places=2)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
                ('created_by', models.ForeignKey(related_name='innovationproject_create_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('recipient', models.ForeignKey(related_name='received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(related_name='sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(null=True, max_length=255)),
                ('title_am', models.CharField(null=True, max_length=255)),
                ('title_bg', models.CharField(null=True, max_length=255)),
                ('title_en', models.CharField(null=True, max_length=255)),
                ('title_uk', models.CharField(null=True, max_length=255)),
                ('title_he', models.CharField(null=True, max_length=255)),
                ('title_ar', models.CharField(null=True, max_length=255)),
                ('title_zh', models.CharField(null=True, max_length=255)),
                ('image', b24online.custom.CustomImageField(storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('short_description', models.TextField()),
                ('short_description_ru', models.TextField(null=True)),
                ('short_description_am', models.TextField(null=True)),
                ('short_description_bg', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_uk', models.TextField(null=True)),
                ('short_description_he', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('short_description_zh', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_bg', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('is_tv', models.BooleanField(default=False)),
                ('video_code', models.CharField(null=True, max_length=255, blank=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_am', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_bg', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_en', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_uk', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_he', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_ar', models.CharField(db_index=True, null=True, max_length=255)),
                ('name_zh', models.CharField(db_index=True, null=True, max_length=255)),
                ('image', b24online.custom.CustomImageField(null=True, upload_to='', storage=b24online.custom.S3ImageStorage(), blank=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, related_name='children', blank=True, to='b24online.NewsCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=200, choices=[('item_creating', 'Creating item in process'), ('item_updating', 'Update item in process'), ('item_created', 'Item created'), ('item_updated', 'Item Updated'), ('error_creating', 'Error in creating')])),
                ('user', models.ForeignKey(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'permissions': (('manage_organization', 'Manage Organization'),),
            },
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('first_name', models.CharField(null=True, max_length=255)),
                ('first_name_ru', models.CharField(null=True, max_length=255)),
                ('first_name_am', models.CharField(null=True, max_length=255)),
                ('first_name_bg', models.CharField(null=True, max_length=255)),
                ('first_name_en', models.CharField(null=True, max_length=255)),
                ('first_name_uk', models.CharField(null=True, max_length=255)),
                ('first_name_he', models.CharField(null=True, max_length=255)),
                ('first_name_ar', models.CharField(null=True, max_length=255)),
                ('first_name_zh', models.CharField(null=True, max_length=255)),
                ('middle_name', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_ru', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_am', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_bg', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_en', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_uk', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_he', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_ar', models.CharField(null=True, max_length=255, blank=True)),
                ('middle_name_zh', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_ru', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_am', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_bg', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_en', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_uk', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_he', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_ar', models.CharField(null=True, max_length=255, blank=True)),
                ('last_name_zh', models.CharField(null=True, max_length=255, blank=True)),
                ('avatar', b24online.custom.CustomImageField(null=True, upload_to=b24online.utils.generate_upload_path, storage=b24online.custom.S3ImageStorage(), max_length=255, blank=True)),
                ('mobile_number', models.CharField(null=True, max_length=255, blank=True)),
                ('site', models.URLField(null=True, max_length=255, blank=True)),
                ('profession', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_ru', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_am', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_bg', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_en', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_uk', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_he', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_ar', models.CharField(null=True, max_length=255, blank=True)),
                ('profession_zh', models.CharField(null=True, max_length=255, blank=True)),
                ('birthday', models.DateField(null=True, blank=True)),
                ('sex', models.CharField(max_length=255, default='male', choices=[('male', 'Male'), ('female', 'Female')])),
                ('user_type', models.CharField(max_length=255, default='individual', choices=[('businessman', 'Businessman'), ('individual', 'Individual')])),
                ('country', models.ForeignKey(to='b24online.Country')),
                ('user', models.OneToOneField(related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='ProjectGroupObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUserObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(null=True, max_length=255)),
                ('title_am', models.CharField(null=True, max_length=255)),
                ('title_bg', models.CharField(null=True, max_length=255)),
                ('title_en', models.CharField(null=True, max_length=255)),
                ('title_uk', models.CharField(null=True, max_length=255)),
                ('title_he', models.CharField(null=True, max_length=255)),
                ('title_ar', models.CharField(null=True, max_length=255)),
                ('title_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_bg', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('is_on_top', models.BooleanField(default=False)),
                ('site_type', models.CharField(max_length=10, default='b2b', choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('user_site', 'User sites')])),
                ('page_type', models.CharField(max_length=200, choices=[('about', 'About'), ('advices', 'Advices'), ('contacts', 'Contacts'), ('buyer', 'To buyer'), ('seller', 'To seller')])),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('title_ru', models.CharField(null=True, max_length=2048)),
                ('title_am', models.CharField(null=True, max_length=2048)),
                ('title_bg', models.CharField(null=True, max_length=2048)),
                ('title_en', models.CharField(null=True, max_length=2048)),
                ('title_uk', models.CharField(null=True, max_length=2048)),
                ('title_he', models.CharField(null=True, max_length=2048)),
                ('title_ar', models.CharField(null=True, max_length=2048)),
                ('title_zh', models.CharField(null=True, max_length=2048)),
                ('slug', models.SlugField(max_length=2048)),
                ('slug_ru', models.SlugField(null=True, max_length=2048)),
                ('slug_am', models.SlugField(null=True, max_length=2048)),
                ('slug_bg', models.SlugField(null=True, max_length=2048)),
                ('slug_en', models.SlugField(null=True, max_length=2048)),
                ('slug_uk', models.SlugField(null=True, max_length=2048)),
                ('slug_he', models.SlugField(null=True, max_length=2048)),
                ('slug_ar', models.SlugField(null=True, max_length=2048)),
                ('slug_zh', models.SlugField(null=True, max_length=2048)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_bg', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('currency', models.CharField(null=True, max_length=255, choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')])),
                ('cost', models.DecimalField(max_digits=15, null=True, decimal_places=2)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
                ('country', models.ForeignKey(to='b24online.Country')),
                ('created_by', models.ForeignKey(related_name='tender_create_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(related_name='vacancy_create_user', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(related_name='vacancies', to='b24online.Department')),
                ('updated_by', models.ForeignKey(related_name='vacancy_update_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, related_name='work_positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, primary_key=True, parent_link=True, serialize=False, to='b24online.Order')),
                ('total_cost', models.DecimalField(max_digits=15, decimal_places=2)),
                ('object_id', models.PositiveIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('price_factor', models.FloatField(default=1)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('b24online.order',),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, primary_key=True, parent_link=True, serialize=False, to='b24online.Advertisement')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(null=True, max_length=255)),
                ('title_am', models.CharField(null=True, max_length=255)),
                ('title_bg', models.CharField(null=True, max_length=255)),
                ('title_en', models.CharField(null=True, max_length=255)),
                ('title_uk', models.CharField(null=True, max_length=255)),
                ('title_he', models.CharField(null=True, max_length=255)),
                ('title_ar', models.CharField(null=True, max_length=255)),
                ('title_zh', models.CharField(null=True, max_length=255)),
                ('link', models.URLField()),
                ('image', b24online.custom.CustomImageField(storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(b24online.models.ActiveModelMixing, 'b24online.advertisement'),
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, primary_key=True, parent_link=True, serialize=False, to='b24online.Organization')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_ru', models.TextField(null=True, blank=True)),
                ('short_description_am', models.TextField(null=True, blank=True)),
                ('short_description_bg', models.TextField(null=True, blank=True)),
                ('short_description_en', models.TextField(null=True, blank=True)),
                ('short_description_uk', models.TextField(null=True, blank=True)),
                ('short_description_he', models.TextField(null=True, blank=True)),
                ('short_description_ar', models.TextField(null=True, blank=True)),
                ('short_description_zh', models.TextField(null=True, blank=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('logo', b24online.custom.CustomImageField(storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path, max_length=255)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('director', models.CharField(max_length=255, blank=True)),
                ('director_ru', models.CharField(null=True, max_length=255, blank=True)),
                ('director_am', models.CharField(null=True, max_length=255, blank=True)),
                ('director_bg', models.CharField(null=True, max_length=255, blank=True)),
                ('director_en', models.CharField(null=True, max_length=255, blank=True)),
                ('director_uk', models.CharField(null=True, max_length=255, blank=True)),
                ('director_he', models.CharField(null=True, max_length=255, blank=True)),
                ('director_ar', models.CharField(null=True, max_length=255, blank=True)),
                ('director_zh', models.CharField(null=True, max_length=255, blank=True)),
                ('address', models.CharField(max_length=2048, blank=True)),
                ('address_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('org_type', models.CharField(max_length=30, choices=[('international', 'International'), ('national', 'National'), ('affiliate', 'Affiliate')])),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('b24online.organization', b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, primary_key=True, parent_link=True, serialize=False, to='b24online.Organization')),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(null=True, max_length=255)),
                ('name_am', models.CharField(null=True, max_length=255)),
                ('name_bg', models.CharField(null=True, max_length=255)),
                ('name_en', models.CharField(null=True, max_length=255)),
                ('name_uk', models.CharField(null=True, max_length=255)),
                ('name_he', models.CharField(null=True, max_length=255)),
                ('name_ar', models.CharField(null=True, max_length=255)),
                ('name_zh', models.CharField(null=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(null=True, max_length=255)),
                ('slug_am', models.SlugField(null=True, max_length=255)),
                ('slug_bg', models.SlugField(null=True, max_length=255)),
                ('slug_en', models.SlugField(null=True, max_length=255)),
                ('slug_uk', models.SlugField(null=True, max_length=255)),
                ('slug_he', models.SlugField(null=True, max_length=255)),
                ('slug_ar', models.SlugField(null=True, max_length=255)),
                ('slug_zh', models.SlugField(null=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_ru', models.TextField(null=True, blank=True)),
                ('short_description_am', models.TextField(null=True, blank=True)),
                ('short_description_bg', models.TextField(null=True, blank=True)),
                ('short_description_en', models.TextField(null=True, blank=True)),
                ('short_description_uk', models.TextField(null=True, blank=True)),
                ('short_description_he', models.TextField(null=True, blank=True)),
                ('short_description_ar', models.TextField(null=True, blank=True)),
                ('short_description_zh', models.TextField(null=True, blank=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_bg', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('logo', b24online.custom.CustomImageField(storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('keywords_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('director', models.CharField(max_length=255, blank=True)),
                ('director_ru', models.CharField(null=True, max_length=255, blank=True)),
                ('director_am', models.CharField(null=True, max_length=255, blank=True)),
                ('director_bg', models.CharField(null=True, max_length=255, blank=True)),
                ('director_en', models.CharField(null=True, max_length=255, blank=True)),
                ('director_uk', models.CharField(null=True, max_length=255, blank=True)),
                ('director_he', models.CharField(null=True, max_length=255, blank=True)),
                ('director_ar', models.CharField(null=True, max_length=255, blank=True)),
                ('director_zh', models.CharField(null=True, max_length=255, blank=True)),
                ('address', models.CharField(max_length=2048, blank=True)),
                ('address_ru', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_am', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_bg', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_en', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_uk', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_he', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_ar', models.CharField(null=True, max_length=2048, blank=True)),
                ('address_zh', models.CharField(null=True, max_length=2048, blank=True)),
                ('slogan', models.CharField(max_length=2048, blank=True)),
                ('company_paypal_account', models.EmailField(null=True, max_length=254, blank=True)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
            ],
            options={
                'ordering': ('tree_id', 'lft'),
                'abstract': False,
            },
            bases=('b24online.organization', b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='ContextAdvertisement',
            fields=[
                ('advertisement_ptr', models.OneToOneField(auto_created=True, primary_key=True, parent_link=True, serialize=False, to='b24online.Advertisement')),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(related_name='contextadvertisement_create_user', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(related_name='contextadvertisement_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(b24online.models.ActiveModelMixing, 'b24online.advertisement'),
        ),
        migrations.AddField(
            model_name='tender',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='tender',
            name='updated_by',
            field=models.ForeignKey(related_name='tender_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='staticpage',
            index_together=set([('page_type', 'site_type')]),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='permission',
            field=models.ForeignKey(to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='group',
            field=models.ForeignKey(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(related_name='organizations', to='b24online.Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(related_name='organization_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(null=True, related_name='children', verbose_name='parent', blank=True, to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='polymorphic_ctype',
            field=models.ForeignKey(null=True, related_name='polymorphic_b24online.organization_set+', editable=False, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(related_name='organization_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='b24online.NewsCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.ForeignKey(null=True, to='b24online.Country'),
        ),
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(related_name='news_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='organization',
            field=models.ForeignKey(null=True, related_name='news', to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_by',
            field=models.ForeignKey(related_name='news_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='organization',
            field=models.ForeignKey(null=True, to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='updated_by',
            field=models.ForeignKey(related_name='innovationproject_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='updated_by',
            field=models.ForeignKey(related_name='exhibition_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(related_name='departments', to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(related_name='department_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='categories',
            field=models.ManyToManyField(to='b24online.BusinessProposalCategory'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='country',
            field=models.ForeignKey(to='b24online.Country'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='created_by',
            field=models.ForeignKey(related_name='businessproposal_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='organization',
            field=models.ForeignKey(related_name='proposals', to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='updated_by',
            field=models.ForeignKey(related_name='businessproposal_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='bannerblock',
            index_together=set([('code', 'block_type')]),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='branches',
            field=models.ManyToManyField(to='b24online.Branch'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='b24online.B2BProductCategory'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='created_by',
            field=models.ForeignKey(related_name='b2bproduct_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='updated_by',
            field=models.ForeignKey(related_name='b2bproduct_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='advertisement_item',
            field=models.ForeignKey(related_name='targets', to='b24online.Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='content_type',
            field=models.ForeignKey(to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='created_by',
            field=models.ForeignKey(related_name='advertisementtarget_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='updated_by',
            field=models.ForeignKey(related_name='advertisementtarget_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set([('recipient', 'sender')]),
        ),
        migrations.AddField(
            model_name='banner',
            name='block',
            field=models.ForeignKey(related_name='banners', to='b24online.BannerBlock'),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_by',
            field=models.ForeignKey(related_name='banner_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='banner',
            name='organization',
            field=models.ForeignKey(null=True, to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='banner',
            name='site',
            field=models.ForeignKey(null=True, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_by',
            field=models.ForeignKey(related_name='banner_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='company',
            field=models.ForeignKey(related_name='b2b_products', to='b24online.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='advertisementprice',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='advertisement',
            field=models.OneToOneField(to='b24online.Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='content_type',
            field=models.ForeignKey(to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='created_by',
            field=models.ForeignKey(related_name='advertisementorder_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='price_components',
            field=models.ManyToManyField(to='b24online.AdvertisementPrice'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='updated_by',
            field=models.ForeignKey(related_name='advertisementorder_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='b2bproduct',
            index_together=set([('created_at', 'company')]),
        ),
    ]
