# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import b24online.custom
import polymorphic_tree.models
from django.conf import settings
import django.utils.timezone
import django.contrib.postgres.fields.ranges
import mptt.fields
import b24online.models
import django.contrib.postgres.fields.hstore
import b24online.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0006_require_contenttypes_0002'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_am', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='additionalpage_create_user')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='additionalpage_update_user')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementPrices',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('advertisement_type', models.CharField(max_length=10, choices=[('banner', 'Banners'), ('context', 'Context Advertisement')])),
                ('object_id', models.PositiveIntegerField()),
                ('dates', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='advertisementprices_create_user')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='advertisementprices_update_user')),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementTarget',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='B2BProduct',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(max_length=2048)),
                ('name_ru', models.CharField(max_length=2048, null=True)),
                ('name_am', models.CharField(max_length=2048, null=True)),
                ('name_en', models.CharField(max_length=2048, null=True)),
                ('name_uk', models.CharField(max_length=2048, null=True)),
                ('name_he', models.CharField(max_length=2048, null=True)),
                ('name_ar', models.CharField(max_length=2048, null=True)),
                ('name_zh', models.CharField(max_length=2048, null=True)),
                ('slug', models.SlugField(max_length=2048)),
                ('slug_ru', models.SlugField(max_length=2048, null=True)),
                ('slug_am', models.SlugField(max_length=2048, null=True)),
                ('slug_en', models.SlugField(max_length=2048, null=True)),
                ('slug_uk', models.SlugField(max_length=2048, null=True)),
                ('slug_he', models.SlugField(max_length=2048, null=True)),
                ('slug_ar', models.SlugField(max_length=2048, null=True)),
                ('slug_zh', models.SlugField(max_length=2048, null=True)),
                ('short_description', models.TextField()),
                ('short_description_ru', models.TextField(null=True)),
                ('short_description_am', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_uk', models.TextField(null=True)),
                ('short_description_he', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('short_description_zh', models.TextField(null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('image', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True, null=True, storage=b24online.custom.S3ImageStorage())),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('currency', models.CharField(max_length=255, choices=[('NIS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble')], blank=True, null=True)),
                ('measurement_unit', models.CharField(max_length=255, choices=[('kg', 'Kilogram'), ('pcs', 'Piece')], blank=True, null=True)),
                ('cost', models.DecimalField(max_digits=15, decimal_places=3, blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='B2BProductCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('image', b24online.custom.CustomImageField(upload_to='', blank=True, null=True, storage=b24online.custom.S3ImageStorage())),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(related_name='children', to='b24online.B2BProductCategory', blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='B2BProductComment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='b2bproductcomment_create_user')),
                ('parent', mptt.fields.TreeForeignKey(related_name='children', to='b24online.B2BProductComment', blank=True, null=True)),
                ('product', models.ForeignKey(to='b24online.B2BProduct')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='b2bproductcomment_update_user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BannerBlock',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', b24online.custom.CustomImageField(upload_to='', blank=True, null=True, storage=b24online.custom.S3ImageStorage())),
                ('description', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_ru', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_am', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_en', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_uk', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_he', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_ar', models.CharField(max_length=1024, blank=True, null=True)),
                ('description_zh', models.CharField(max_length=1024, blank=True, null=True)),
                ('factor', models.FloatField(default=1)),
                ('block_type', models.CharField(max_length=10, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('user_site', 'User sites')])),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(related_name='children', to='b24online.Branch', blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='BusinessProposal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_am', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='BusinessProposalCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(related_name='children', to='b24online.BusinessProposalCategory', blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('flag', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
            ],
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='department_create_user')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255, null=True)),
                ('description_am', models.CharField(max_length=255, null=True)),
                ('description_en', models.CharField(max_length=255, null=True)),
                ('description_uk', models.CharField(max_length=255, null=True)),
                ('description_he', models.CharField(max_length=255, null=True)),
                ('description_ar', models.CharField(max_length=255, null=True)),
                ('description_zh', models.CharField(max_length=255, null=True)),
                ('document', models.FileField(upload_to=b24online.utils.document_upload_path)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='document_create_user')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='document_update_user')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_am', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('city_ru', models.CharField(max_length=255, null=True)),
                ('city_am', models.CharField(max_length=255, null=True)),
                ('city_en', models.CharField(max_length=255, null=True)),
                ('city_uk', models.CharField(max_length=255, null=True)),
                ('city_he', models.CharField(max_length=255, null=True)),
                ('city_ar', models.CharField(max_length=255, null=True)),
                ('city_zh', models.CharField(max_length=255, null=True)),
                ('route', models.CharField(max_length=2048, blank=True)),
                ('route_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('route_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('route_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('route_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('route_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('route_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('route_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
                ('country', models.ForeignKey(to='b24online.Country')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='exhibition_create_user')),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=266, null=True)),
                ('title_ru', models.CharField(max_length=266, null=True)),
                ('title_am', models.CharField(max_length=266, null=True)),
                ('title_en', models.CharField(max_length=266, null=True)),
                ('title_uk', models.CharField(max_length=266, null=True)),
                ('title_he', models.CharField(max_length=266, null=True)),
                ('title_ar', models.CharField(max_length=266, null=True)),
                ('title_zh', models.CharField(max_length=266, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='gallery_create_user')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='gallery_update_user')),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('image', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, storage=b24online.custom.S3ImageStorage())),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='galleryimage_create_user')),
                ('gallery', models.ForeignKey(to='b24online.Gallery', related_name='gallery_items')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='galleryimage_update_user')),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('photo', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True, storage=b24online.custom.S3ImageStorage())),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_name_ru', models.CharField(max_length=255, null=True)),
                ('organization_name_am', models.CharField(max_length=255, null=True)),
                ('organization_name_en', models.CharField(max_length=255, null=True)),
                ('organization_name_uk', models.CharField(max_length=255, null=True)),
                ('organization_name_he', models.CharField(max_length=255, null=True)),
                ('organization_name_ar', models.CharField(max_length=255, null=True)),
                ('organization_name_zh', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('position_name', models.CharField(max_length=255)),
                ('position_name_ru', models.CharField(max_length=255, null=True)),
                ('position_name_am', models.CharField(max_length=255, null=True)),
                ('position_name_en', models.CharField(max_length=255, null=True)),
                ('position_name_uk', models.CharField(max_length=255, null=True)),
                ('position_name_he', models.CharField(max_length=255, null=True)),
                ('position_name_ar', models.CharField(max_length=255, null=True)),
                ('position_name_zh', models.CharField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
            ],
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='InnovationProject',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(max_length=2048)),
                ('name_ru', models.CharField(max_length=2048, null=True)),
                ('name_am', models.CharField(max_length=2048, null=True)),
                ('name_en', models.CharField(max_length=2048, null=True)),
                ('name_uk', models.CharField(max_length=2048, null=True)),
                ('name_he', models.CharField(max_length=2048, null=True)),
                ('name_ar', models.CharField(max_length=2048, null=True)),
                ('name_zh', models.CharField(max_length=2048, null=True)),
                ('slug', models.SlugField(max_length=2048)),
                ('slug_ru', models.SlugField(max_length=2048, null=True)),
                ('slug_am', models.SlugField(max_length=2048, null=True)),
                ('slug_en', models.SlugField(max_length=2048, null=True)),
                ('slug_uk', models.SlugField(max_length=2048, null=True)),
                ('slug_he', models.SlugField(max_length=2048, null=True)),
                ('slug_ar', models.SlugField(max_length=2048, null=True)),
                ('slug_zh', models.SlugField(max_length=2048, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('product_name', models.CharField(max_length=2048)),
                ('product_name_ru', models.CharField(max_length=2048, null=True)),
                ('product_name_am', models.CharField(max_length=2048, null=True)),
                ('product_name_en', models.CharField(max_length=2048, null=True)),
                ('product_name_uk', models.CharField(max_length=2048, null=True)),
                ('product_name_he', models.CharField(max_length=2048, null=True)),
                ('product_name_ar', models.CharField(max_length=2048, null=True)),
                ('product_name_zh', models.CharField(max_length=2048, null=True)),
                ('business_plan', models.TextField()),
                ('business_plan_ru', models.TextField(null=True)),
                ('business_plan_am', models.TextField(null=True)),
                ('business_plan_en', models.TextField(null=True)),
                ('business_plan_uk', models.TextField(null=True)),
                ('business_plan_he', models.TextField(null=True)),
                ('business_plan_ar', models.TextField(null=True)),
                ('business_plan_zh', models.TextField(null=True)),
                ('currency', models.CharField(max_length=255, choices=[('NIS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble')], null=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='innovationproject_create_user')),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('is_read', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='received')),
                ('sender', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='sent')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_am', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('image', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True, storage=b24online.custom.S3ImageStorage())),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('short_description', models.TextField()),
                ('short_description_ru', models.TextField(null=True)),
                ('short_description_am', models.TextField(null=True)),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_uk', models.TextField(null=True)),
                ('short_description_he', models.TextField(null=True)),
                ('short_description_ar', models.TextField(null=True)),
                ('short_description_zh', models.TextField(null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('is_tv', models.BooleanField(default=False)),
                ('video_code', models.CharField(max_length=255, blank=True, null=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('image', b24online.custom.CustomImageField(upload_to='', blank=True, null=True, storage=b24online.custom.S3ImageStorage())),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(related_name='children', to='b24online.NewsCategory', blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('read', models.BooleanField(default=False)),
                ('message', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=200, choices=[('item_creating', 'Creating item in process'), ('item_updating', 'Update item in process'), ('item_created', 'Item created'), ('item_updated', 'Item Updated'), ('error_creating', 'Error in creating')])),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='notifications')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'permissions': (('manage_organization', 'Manage Organization'),),
            },
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('first_name_ru', models.CharField(max_length=255, null=True)),
                ('first_name_am', models.CharField(max_length=255, null=True)),
                ('first_name_en', models.CharField(max_length=255, null=True)),
                ('first_name_uk', models.CharField(max_length=255, null=True)),
                ('first_name_he', models.CharField(max_length=255, null=True)),
                ('first_name_ar', models.CharField(max_length=255, null=True)),
                ('first_name_zh', models.CharField(max_length=255, null=True)),
                ('middle_name', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_ru', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_am', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_en', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_uk', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_he', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_ar', models.CharField(max_length=255, blank=True, null=True)),
                ('middle_name_zh', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_ru', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_am', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_en', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_uk', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_he', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_ar', models.CharField(max_length=255, blank=True, null=True)),
                ('last_name_zh', models.CharField(max_length=255, blank=True, null=True)),
                ('avatar', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, blank=True, null=True, storage=b24online.custom.S3ImageStorage())),
                ('mobile_number', models.CharField(max_length=255, blank=True, null=True)),
                ('site', models.URLField(max_length=255, blank=True, null=True)),
                ('profession', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_ru', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_am', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_en', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_uk', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_he', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_ar', models.CharField(max_length=255, blank=True, null=True)),
                ('profession_zh', models.CharField(max_length=255, blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=255, choices=[('male', 'Male'), ('female', 'Female')], default='male')),
                ('user_type', models.CharField(max_length=255, choices=[('businessman', 'Businessman'), ('individual', 'Individual')], default='individual')),
                ('country', models.ForeignKey(to='b24online.Country')),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL, related_name='profile')),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='ProjectGroupObjectPermission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectUserObjectPermission',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_am', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('is_on_top', models.BooleanField(default=False)),
                ('site_type', models.CharField(max_length=10, choices=[('b2b', 'B2B'), ('b2c', 'B2C'), ('user_site', 'User sites')])),
                ('page_type', models.CharField(max_length=200, choices=[('about', 'About'), ('advices', 'Advices'), ('contacts', 'Contacts'), ('buyer', 'To buyer'), ('seller', 'To seller')])),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=2048)),
                ('title_ru', models.CharField(max_length=2048, null=True)),
                ('title_am', models.CharField(max_length=2048, null=True)),
                ('title_en', models.CharField(max_length=2048, null=True)),
                ('title_uk', models.CharField(max_length=2048, null=True)),
                ('title_he', models.CharField(max_length=2048, null=True)),
                ('title_ar', models.CharField(max_length=2048, null=True)),
                ('title_zh', models.CharField(max_length=2048, null=True)),
                ('slug', models.SlugField(max_length=2048)),
                ('slug_ru', models.SlugField(max_length=2048, null=True)),
                ('slug_am', models.SlugField(max_length=2048, null=True)),
                ('slug_en', models.SlugField(max_length=2048, null=True)),
                ('slug_uk', models.SlugField(max_length=2048, null=True)),
                ('slug_he', models.SlugField(max_length=2048, null=True)),
                ('slug_ar', models.SlugField(max_length=2048, null=True)),
                ('slug_zh', models.SlugField(max_length=2048, null=True)),
                ('content', models.TextField()),
                ('content_ru', models.TextField(null=True)),
                ('content_am', models.TextField(null=True)),
                ('content_en', models.TextField(null=True)),
                ('content_uk', models.TextField(null=True)),
                ('content_he', models.TextField(null=True)),
                ('content_ar', models.TextField(null=True)),
                ('content_zh', models.TextField(null=True)),
                ('currency', models.CharField(max_length=255, choices=[('NIS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble')], null=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
                ('country', models.ForeignKey(to='b24online.Country')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='tender_create_user')),
            ],
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='vacancy_create_user')),
                ('department', models.ForeignKey(to='b24online.Department', related_name='vacancies')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='vacancy_update_user')),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='work_positions', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementOrder',
            fields=[
                ('order_ptr', models.OneToOneField(to='b24online.Order', parent_link=True, serialize=False, primary_key=True, auto_created=True)),
                ('total_cost', models.DecimalField(decimal_places=3, max_digits=15)),
                ('object_id', models.PositiveIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('price_factor', models.FloatField(default=1)),
                ('dates', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('b24online.order',),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('advertisement_ptr', models.OneToOneField(to='b24online.Advertisement', parent_link=True, serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_am', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uk', models.CharField(max_length=255, null=True)),
                ('title_he', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_zh', models.CharField(max_length=255, null=True)),
                ('link', models.URLField()),
                ('image', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, storage=b24online.custom.S3ImageStorage())),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(b24online.models.ActiveModelMixing, 'b24online.advertisement'),
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('organization_ptr', models.OneToOneField(to='b24online.Organization', parent_link=True, serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('name_ru', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_am', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_en', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_uk', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_he', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True)),
                ('name_zh', models.CharField(db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_ru', models.TextField(blank=True, null=True)),
                ('short_description_am', models.TextField(blank=True, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_uk', models.TextField(blank=True, null=True)),
                ('short_description_he', models.TextField(blank=True, null=True)),
                ('short_description_ar', models.TextField(blank=True, null=True)),
                ('short_description_zh', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('logo', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, storage=b24online.custom.S3ImageStorage())),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('director', models.CharField(max_length=255, blank=True)),
                ('director_ru', models.CharField(max_length=255, blank=True, null=True)),
                ('director_am', models.CharField(max_length=255, blank=True, null=True)),
                ('director_en', models.CharField(max_length=255, blank=True, null=True)),
                ('director_uk', models.CharField(max_length=255, blank=True, null=True)),
                ('director_he', models.CharField(max_length=255, blank=True, null=True)),
                ('director_ar', models.CharField(max_length=255, blank=True, null=True)),
                ('director_zh', models.CharField(max_length=255, blank=True, null=True)),
                ('address', models.CharField(max_length=2048, blank=True)),
                ('address_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('org_type', models.CharField(max_length=30, choices=[('international', 'International'), ('national', 'National'), ('affiliate', 'Affiliate')])),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'abstract': False,
                'ordering': ('tree_id', 'lft'),
            },
            bases=('b24online.organization', b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('organization_ptr', models.OneToOneField(to='b24online.Organization', parent_link=True, serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255, null=True)),
                ('name_am', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_uk', models.CharField(max_length=255, null=True)),
                ('name_he', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_zh', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('slug_ru', models.SlugField(max_length=255, null=True)),
                ('slug_am', models.SlugField(max_length=255, null=True)),
                ('slug_en', models.SlugField(max_length=255, null=True)),
                ('slug_uk', models.SlugField(max_length=255, null=True)),
                ('slug_he', models.SlugField(max_length=255, null=True)),
                ('slug_ar', models.SlugField(max_length=255, null=True)),
                ('slug_zh', models.SlugField(max_length=255, null=True)),
                ('short_description', models.TextField(blank=True)),
                ('short_description_ru', models.TextField(blank=True, null=True)),
                ('short_description_am', models.TextField(blank=True, null=True)),
                ('short_description_en', models.TextField(blank=True, null=True)),
                ('short_description_uk', models.TextField(blank=True, null=True)),
                ('short_description_he', models.TextField(blank=True, null=True)),
                ('short_description_ar', models.TextField(blank=True, null=True)),
                ('short_description_zh', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_am', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uk', models.TextField(null=True)),
                ('description_he', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_zh', models.TextField(null=True)),
                ('logo', b24online.custom.CustomImageField(upload_to=b24online.utils.generate_upload_path, max_length=255, storage=b24online.custom.S3ImageStorage())),
                ('keywords', models.CharField(max_length=2048, blank=True)),
                ('keywords_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('keywords_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('director', models.CharField(max_length=255, blank=True)),
                ('director_ru', models.CharField(max_length=255, blank=True, null=True)),
                ('director_am', models.CharField(max_length=255, blank=True, null=True)),
                ('director_en', models.CharField(max_length=255, blank=True, null=True)),
                ('director_uk', models.CharField(max_length=255, blank=True, null=True)),
                ('director_he', models.CharField(max_length=255, blank=True, null=True)),
                ('director_ar', models.CharField(max_length=255, blank=True, null=True)),
                ('director_zh', models.CharField(max_length=255, blank=True, null=True)),
                ('address', models.CharField(max_length=2048, blank=True)),
                ('address_ru', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_am', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_en', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_uk', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_he', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_ar', models.CharField(max_length=2048, blank=True, null=True)),
                ('address_zh', models.CharField(max_length=2048, blank=True, null=True)),
                ('slogan', models.CharField(max_length=2048, blank=True)),
                ('metadata', django.contrib.postgres.fields.hstore.HStoreField()),
                ('branches', models.ManyToManyField(to='b24online.Branch')),
            ],
            options={
                'abstract': False,
                'ordering': ('tree_id', 'lft'),
            },
            bases=('b24online.organization', b24online.models.IndexedModelMixin),
        ),
        migrations.CreateModel(
            name='ContextAdvertisement',
            fields=[
                ('advertisement_ptr', models.OneToOneField(to='b24online.Advertisement', parent_link=True, serialize=False, primary_key=True, auto_created=True)),
                ('object_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(to='contenttypes.ContentType')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='contextadvertisement_create_user')),
                ('updated_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='contextadvertisement_update_user')),
            ],
            bases=(b24online.models.ActiveModelMixing, 'b24online.advertisement'),
        ),
        migrations.AddField(
            model_name='tender',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='tender',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='tender_update_user'),
        ),
        migrations.AlterIndexTogether(
            name='staticpage',
            index_together=set([('page_type', 'site_type')]),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='permission',
            field=models.ForeignKey(to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='projectuserobjectpermission',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='group',
            field=models.ForeignKey(to='auth.Group'),
        ),
        migrations.AddField(
            model_name='projectgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(related_name='organizations', to='b24online.Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='organization_create_user'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=polymorphic_tree.models.PolymorphicTreeForeignKey(related_name='children', blank=True, null=True, to='b24online.Organization', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='organization',
            name='polymorphic_ctype',
            field=models.ForeignKey(related_name='polymorphic_b24online.organization_set+', to='contenttypes.ContentType', null=True, editable=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='organization_update_user'),
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(to='b24online.NewsCategory'),
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.ForeignKey(to='b24online.Country', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='news_create_user'),
        ),
        migrations.AddField(
            model_name='news',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization', related_name='news', null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='news_update_user'),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization', null=True),
        ),
        migrations.AddField(
            model_name='innovationproject',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='innovationproject_update_user'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='exhibition_update_user'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization', related_name='departments'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='department_update_user'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='categories',
            field=models.ManyToManyField(to='b24online.BusinessProposalCategory'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='country',
            field=models.ForeignKey(to='b24online.Country'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='businessproposal_create_user'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization', related_name='proposals'),
        ),
        migrations.AddField(
            model_name='businessproposal',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='businessproposal_update_user'),
        ),
        migrations.AlterIndexTogether(
            name='bannerblock',
            index_together=set([('code', 'block_type')]),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='branches',
            field=models.ManyToManyField(to='b24online.Branch'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='b24online.B2BProductCategory'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='b2bproduct_create_user'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='b2bproduct_update_user'),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='advertisement_item',
            field=models.ForeignKey(to='b24online.Advertisement', related_name='targets'),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='content_type',
            field=models.ForeignKey(to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='advertisementtarget_create_user'),
        ),
        migrations.AddField(
            model_name='advertisementtarget',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='advertisementtarget_update_user'),
        ),
        migrations.AlterIndexTogether(
            name='tender',
            index_together=set([('is_active', 'is_deleted', 'created_at')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectuserobjectpermission',
            unique_together=set([('user', 'permission', 'content_object')]),
        ),
        migrations.AlterUniqueTogether(
            name='projectgroupobjectpermission',
            unique_together=set([('group', 'permission', 'content_object')]),
        ),
        migrations.AlterIndexTogether(
            name='organization',
            index_together=set([('is_active', 'is_deleted', 'created_at')]),
        ),
        migrations.AlterIndexTogether(
            name='news',
            index_together=set([('is_active', 'is_deleted', 'created_at')]),
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set([('recipient', 'sender')]),
        ),
        migrations.AlterIndexTogether(
            name='innovationproject',
            index_together=set([('is_active', 'is_deleted', 'created_at')]),
        ),
        migrations.AlterIndexTogether(
            name='exhibition',
            index_together=set([('is_active', 'is_deleted', 'created_at')]),
        ),
        migrations.AlterIndexTogether(
            name='businessproposal',
            index_together=set([('is_active', 'is_deleted', 'created_at')]),
        ),
        migrations.AddField(
            model_name='banner',
            name='block',
            field=models.ForeignKey(to='b24online.BannerBlock', related_name='banners'),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='banner_create_user'),
        ),
        migrations.AddField(
            model_name='banner',
            name='organization',
            field=models.ForeignKey(to='b24online.Organization', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='site',
            field=models.ForeignKey(to='sites.Site', null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='banner_update_user'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='company',
            field=models.ForeignKey(to='b24online.Company', related_name='b2b_products'),
        ),
        migrations.AlterUniqueTogether(
            name='advertisementprices',
            unique_together=set([('content_type', 'object_id')]),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='advertisement',
            field=models.OneToOneField(to='b24online.Advertisement'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='content_type',
            field=models.ForeignKey(to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='advertisementorder_create_user'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='price_components',
            field=models.ManyToManyField(to='b24online.AdvertisementPrices'),
        ),
        migrations.AddField(
            model_name='advertisementorder',
            name='updated_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, related_name='advertisementorder_update_user'),
        ),
        migrations.AlterIndexTogether(
            name='contextadvertisement',
            index_together=set([('content_type', 'is_active')]),
        ),
        migrations.AlterIndexTogether(
            name='b2bproduct',
            index_together=set([('is_active', 'is_deleted', 'created_at', 'company')]),
        ),
    ]
