# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 10:10
from __future__ import unicode_literals

import b24online.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('b24online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('deal_no', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Deal No.')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='Total deal cost')),
                ('total_cost_data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True, verbose_name='Total cost data')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Payment datetime')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('paid', 'Paid'), ('ordered', 'Ordered by Email')], default='draft', editable=False, max_length=10, verbose_name='Deal status')),
                ('person_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('person_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('person_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone number')),
                ('person_address', models.CharField(blank=True, max_length=2048, verbose_name='Address')),
                ('person_email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Purchase deal',
                'verbose_name_plural': 'Purchase deal',
            },
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.CreateModel(
            name='DealItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='The product price')),
                ('currency', models.CharField(blank=True, choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')], max_length=255, null=True, verbose_name='Currence')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('deal', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='item_deal', to='b24online.Deal', verbose_name='Deal')),
            ],
            options={
                'verbose_name': 'Deal product',
                'verbose_name_plural': 'Deal products',
            },
        ),
        migrations.CreateModel(
            name='DealOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('customer_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], max_length=10, verbose_name='Customer type')),
                ('order_no', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Order No.')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='Total order cost')),
                ('total_cost_data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True, verbose_name='Total cost data')),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Payment datetime')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('partially', 'Partially paid'), ('paid', 'Paid')], default='draft', editable=False, max_length=10, verbose_name='Order status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealorder_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('customer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_company', to='b24online.Company', verbose_name='Customer company')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealorder_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Product order',
                'verbose_name_plural': 'Product orders',
            },
            bases=(b24online.models.ActiveModelMixing, models.Model),
        ),
        migrations.AlterField(
            model_name='registeredevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='registeredevent',
            name='is_unique',
            field=models.BooleanField(default=False, verbose_name='Is unique'),
        ),
        migrations.AlterField(
            model_name='registeredevent',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='deal',
            name='deal_order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='deals_list', to='b24online.DealOrder', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='deal',
            name='person_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b24online.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='deal',
            name='supplier_company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_company', to='b24online.Company', verbose_name='Supplier company'),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
    ]
