# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0002_auto_20160203_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='total_cost_data',
        ),
        migrations.RemoveField(
            model_name='dealorder',
            name='customer_company',
        ),
        migrations.RemoveField(
            model_name='dealorder',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='dealorder',
            name='total_cost_data',
        ),
        migrations.AddField(
            model_name='deal',
            name='currency',
            field=models.CharField(blank=True, choices=[('ILS', 'Israeli New Sheqel'), ('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('RUB', 'Russian Ruble'), ('BGN', 'Bulgarian Lev'), ('BYR', 'Belarusian Ruble')], max_length=255, null=True, verbose_name='Currence'),
        ),
        migrations.AddField(
            model_name='dealorder',
            name='customer_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deal_orders', to='b24online.Organization', verbose_name='Customer organization'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='deal_order',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='order_deals', to='b24online.DealOrder', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='supplier_company',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='company_deals', to='b24online.Company', verbose_name='Supplier company'),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='deal',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='deal_products', to='b24online.Deal', verbose_name='Deal'),
        ),
        migrations.AlterField(
            model_name='dealitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='dealorder',
            name='customer_type',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], max_length=15, verbose_name='Customer type'),
        ),
    ]
