# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('b24online', '0003_auto_20160218_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('file_name', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='File name')),
                ('content_type', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Content type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messageattachment_create_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message attachment',
                'verbose_name_plural': 'Messages attachments',
            },
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('subject', models.CharField(max_length=255, null=True, verbose_name='Chat subject')),
                ('is_private', models.NullBooleanField()),
                ('status', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed')], db_index=True, default='opened', editable=False, max_length=10, verbose_name='Chart status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagechat_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='b24online.Organization')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_chats', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messagechat_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Messages chat',
                'verbose_name_plural': 'Messages chats',
            },
        ),
        migrations.CreateModel(
            name='PermissionsExtraGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Group name')),
                ('permissions', models.ManyToManyField(to='auth.Permission', verbose_name='Permission extra group')),
            ],
            options={
                'verbose_name': "Permission's extra group",
                'verbose_name_plural': "Permission's extra groups",
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Vacancy group')),
            ],
            options={
                'verbose_name': 'Group for staff',
                'verbose_name_plural': 'Groups for staff',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_messages', to='b24online.Organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('read', 'Read')], db_index=True, default='draft', editable=False, max_length=10, verbose_name='Message status'),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Chat subject'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='is_hidden_user',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Hide the vacancy user'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('paid', 'Paid'), ('ordered', 'Ordered by Email'), ('rejected', 'Rejected')], default='draft', editable=False, max_length=10, verbose_name='Deal status'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='b24online.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='b24online.MessageChat'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='permission_extra_group',
            field=models.ManyToManyField(related_name='extra_group_vacancies', to='b24online.PermissionsExtraGroup'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='staffgroup',
            field=models.ManyToManyField(related_name='group_vacancies', to='b24online.StaffGroup'),
        ),
    ]
