# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 07:48
from __future__ import unicode_literals

import b24online.custom
import b24online.models
import b24online.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0004_auto_20160218_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripion')),
                ('logo', b24online.custom.CustomImageField(max_length=255, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path)),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
            ],
            options={
                'verbose_name_plural': 'Products producers',
                'verbose_name': 'Products producer',
            },
            bases=(models.Model, b24online.models.IndexedModelMixin),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='dealorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='messagechat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Update time'),
        ),
        migrations.AddField(
            model_name='b2bproduct',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b2b_products', to='b24online.Producer', verbose_name='Producer'),
        ),
    ]
