# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 12:18
from __future__ import unicode_literals

import b24online.custom
import b24online.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0005_auto_20160229_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_am',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='short_description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_am',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_ar',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_bg',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_he',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_uk',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug_zh',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='logo',
            field=b24online.custom.CustomImageField(blank=True, max_length=255, null=True, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path),
        ),
    ]
