# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0007_auto_20160329_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='green_level',
            field=models.PositiveIntegerField(default=0, verbose_name="How many coincedences for 'green' color"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='red_level',
            field=models.PositiveIntegerField(default=0, verbose_name="How many coincedences for 'red' color"),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='yellow_level',
            field=models.PositiveIntegerField(default=0, verbose_name="How many coincedences for 'yellow' color"),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='for_color',
            field=models.CharField(blank=True, choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], max_length=10, null=True, verbose_name='For what color'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='b24online.Questionnaire'),
            preserve_default=False,
        ),
    ]
