# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0008_auto_20160331_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='show_answer',
            field=models.NullBooleanField(default=False, verbose_name='Show'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='use_show_result',
            field=models.BooleanField(default=False, verbose_name='Use the option "Show the question if someone selected"'),
        ),
    ]
