# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0009_auto_20160402_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_by_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='b24online.QuestionnaireParticipant'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='User question approved by questionnaire author'),
        ),
    ]
