# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 07:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0010_auto_20160505_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealitem',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extra parameters values'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_am',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_am',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ar',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_bg',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_en',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_he',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ru',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_uk',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_zh',
            field=models.TextField(null=True, verbose_name='Question text'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_am',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_am',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='name_zh',
            field=models.CharField(max_length=255, null=True, verbose_name='Questionnaire title'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_am',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='short_description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Short description'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_am',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_he',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='description_zh',
            field=models.TextField(blank=True, null=True, verbose_name='Descripion'),
        ),
    ]
