# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0011_auto_20160516_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealitem',
            old_name='extra',
            new_name='extra_params',
        ),
        migrations.AddField(
            model_name='dealorder',
            name='deal_place',
            field=models.CharField(choices=[('portal', 'On portal'), ('site', 'On site')], default='portal', max_length=15, verbose_name='Deal place'),
        ),
    ]
