# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 20:31
from __future__ import unicode_literals

import b24online.custom
import b24online.models
import b24online.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0012_auto_20160519_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', b24online.custom.CustomImageField(blank=True, max_length=255, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path)),
                ('slug', models.SlugField(max_length=255)),
                ('short_description', models.TextField()),
                ('content', models.TextField()),
                ('video_code', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.CharField(blank=True, max_length=2048)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_create_user', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video', to='b24online.Organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=(b24online.models.ActiveModelMixing, models.Model, b24online.models.IndexedModelMixin),
        ),
    ]
