# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0013_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='content_am',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='content_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='b24online.Country'),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_am',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_ar',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_bg',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_en',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_he',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_ru',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_uk',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='keywords_zh',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_am',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_bg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_he',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='short_description_zh',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_am',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_ar',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_bg',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_he',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_uk',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug_zh',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_am',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_he',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_zh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
