# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0014_auto_20160526_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='link',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
