# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0015_auto_20160530_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='paypal_txn_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('paypal', 'Paid by PayPal'), ('paid', 'Paid'), ('ordered', 'Ordered by Email'), ('rejected', 'Rejected')], default='draft', editable=False, max_length=10, verbose_name='Deal status'),
        ),
    ]
