# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 22:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0018_leadsstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadsstore',
            name='subject',
        ),
        migrations.AddField(
            model_name='leadsstore',
            name='realname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leadsstore',
            name='url_path',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='leadsstore',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='leadsstore',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='b24online.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leadsstore',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
