# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 18:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0020_auto_20160731_1934'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='b2bproductcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='b2bproductcomment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='branch',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='businessproposalcategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='chamber',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='newscategory',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='organization',
            managers=[
            ],
        ),
    ]
