# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('b24online', '0022_auto_20161016_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementtarget',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterIndexTogether(
            name='advertisementtarget',
            index_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='contextadvertisement',
            index_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='dealitem',
            index_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together=set([('content_type', 'object_id')]),
        ),
        migrations.AlterIndexTogether(
            name='gallery',
            index_together=set([('content_type', 'object_id')]),
        ),
    ]
