# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0024_auto_20161024_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='description_am',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_ar',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_bg',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_en',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_es',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_he',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_ru',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_uk',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_zh',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
