# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 18:45
from __future__ import unicode_literals

import b24online.custom
import b24online.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0027_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=b24online.custom.CustomImageField(blank=True, max_length=255, null=True, storage=b24online.custom.S3ImageStorage(), upload_to=b24online.utils.generate_upload_path),
        ),
    ]
