# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0028_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChannel',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('b24online.news',),
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
