# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b24online', '0031_auto_20170420_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalparameters',
            name='extra_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
