from django.conf.urls import url

from b24online.Product.views import (B2BProductList, B2CProductList,
    B2CPCouponsList, B2BProductCreate, B2BProductUpdate,
    B2CProductCreate, B2CProductUpdate, B2BProductDelete,
    B2CProductDelete, categories_list, B2BProductDetail,
    B2CProductDetail, ProductGalleryImageList, DeleteProductGalleryImage,
    ProductDocumentList, DeleteProductDocument, DealOrderList, DealOrderDetail,
    DealOrderPayment, DealPayPal, DealList, DealDetail, DealPayment,
    DealItemDelete, DealItemDetail, B2BProductUpdateList, B2CProductUpdateList,
    category_tree_json, category_tree_demo, ProducerList, ProducerCreate,
    ProducerUpdate, ProducerDelete, ExtraParamsList, ExtraParamsCreate,
    ExtraParamsUpdate, ExtraParamsDelete)

from b24online.models import B2BProductCategory
from centerpokupok.models import B2CProductCategory

urlpatterns = [

    url(r'^b2b/$', B2BProductList.as_view(), name='main'),
    url(r'^page(?P<page>[0-9]+)?/$', B2BProductList.as_view(), name="paginator"),
    url(r'^my/$', B2BProductList.as_view(my=True), name='my_main'),
    url(r'^my/page(?P<page>[0-9]+)?/$', B2BProductList.as_view(my=True), name="my_main_paginator"),
    url(r'^my/update/$', B2BProductUpdateList.as_view(my=True),
        name='b2b_product_update'),
    url(r'^my/update/page(?P<page>[0-9]+)?/$',
        B2BProductUpdateList.as_view(my=True),
        name="b2b_product_update_paginator"),
    url(r'^b2c/$', B2CProductList.as_view(), name='main_b2c'),
    #url(r'^b2c/category/tree$', B2CProductList.as_view(), name='main_b2c'),
    url(r'^my_b2c/$', B2CProductList.as_view(my=True), name='my_b2c'),
    url(r'^b2c/page(?P<page>[0-9]+)?/$', B2CProductList.as_view(), name="main_b2c_paginator"),
    url(r'^my_b2c/page(?P<page>[0-9]+)?/$', B2CProductList.as_view(my=True), name="my_b2c_paginator"),
    url(r'^my_b2c/update/$', B2CProductUpdateList.as_view(my=True),
        name='b2c_product_update'),
    url(r'^my_b2c/update/page(?P<page>[0-9]+)?/$',
        B2CProductUpdateList.as_view(my=True),
        name="b2c_product_update_paginator"),
    url(r'^coupons/$', B2CPCouponsList.as_view(), name='main_coupons'),
    url(r'^coupons/page(?P<page>[0-9]+)?/$', B2CPCouponsList.as_view(), name="coupons_paginator"),
    url(r'^add/$', B2BProductCreate.as_view(), name="add"),
    url(r'^add-b2c/$', B2CProductCreate.as_view(), name="addB2C"),
    url(r'^update/(?P<pk>[0-9]+)/$', B2BProductUpdate.as_view(), name="update"),
    url(r'^update-b2c/(?P<pk>[0-9]+)/$', B2CProductUpdate.as_view(), name="updateB2C"),
    url(r'^delete/(?P<pk>[0-9]+)/$', B2BProductDelete.as_view(), name="delete"),
    url(r'^delete-b2c/(?P<pk>[0-9]+)/$', B2CProductDelete.as_view(), name="deleteB2C"),
    url(r'^category-list$', categories_list, {'model': B2BProductCategory}, name="B2BCategoryList"),
    url(r'^category-list-b2c$', categories_list, {'model': B2CProductCategory}, name="B2CCategoryList"),

    # B2B & B2C Detail urls
    url(r'^b2b/(?P<slug>[a-zA-z0-9-]+)-(?P<item_id>[0-9]+)\.html$',
        B2BProductDetail.as_view(), name="detail"),
    url(r'^b2c/(?P<slug>[a-zA-z0-9-]+)-(?P<item_id>[0-9]+)\.html$',
        B2CProductDetail.as_view(), name="B2CDetail"),

    # B2B & B2C Gallery urls
    url(r'^tabs/gallery/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/$',
        ProductGalleryImageList.as_view(), name="tabs_gallery"),
    url(r'^tabs/gallery/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/page(?P<page>[0-9]+)/$',
        ProductGalleryImageList.as_view(), name="tabs_gallery_paged"),
    url(r'^tabs/gallery_structure/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/page(?P<page>[0-9]+)/$',
        ProductGalleryImageList.as_view(is_structure=True), name="gallery_structure"),
    url(r'^tabs/gallery/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/remove/(?P<pk>[0-9]+)/$',
        DeleteProductGalleryImage.as_view(), name="gallery_remove_item"),

    # B2B & B2C Document urls
    url(r'^tabs/documents/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/$',
        ProductDocumentList.as_view(), name="tabs_documents"),
    url(r'^tabs/documents/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/page(?P<page>[0-9]+)/$',
        ProductDocumentList.as_view(), name="tabs_documents_paged"),
    url(r'^tabs/documents_structure/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/page(?P<page>[0-9]+)/$',
        ProductDocumentList.as_view(is_structure=True), name="documents_structure"),
    url(r'^tabs/documents/(?P<type>[b(2b|2c)]{3,})/(?P<item>[0-9]+)/remove/(?P<pk>[0-9]+)/$',
        DeleteProductDocument.as_view(), name="documents_remove_item"),

    # Urls for orders and deals
    url(r'^orders/(?P<item_id>[0-9]+)/$',
        DealOrderDetail.as_view(), name='deal_order_detail'),
    url(r'^orders/(?P<item_id>[0-9]+)/pay/$',
        DealOrderPayment.as_view(), name='deal_order_payment'),
    url(r'^orders/$',
        DealOrderList.as_view(), name='deal_order_list'),
    url(r'^orders/basket/$', DealOrderList.as_view(),
        {'status': 'basket'}, name='deal_order_basket'),
    url(r'^orders/(?P<status>draft|ready|partially|paid|basket)/$',
        DealOrderList.as_view(), name='deal_order_filtered_list'),
    url(r'^deals/(?P<item_id>[0-9]+)/$',
        DealDetail.as_view(), name='deal_detail'),
    url(r'^deals/(?P<item_id>[0-9]+)/pay/$',
        DealPayment.as_view(), name='deal_payment'),
    url(r'^deals/(?P<item_id>[0-9]+)/paypal/$',
        DealPayPal.as_view(), name='deal_paypal'),
    url(r'^deals/$',
        DealList.as_view(), name='deal_list'),
    url(r'^deals/page(?P<page>[0-9]+)?/$',
        DealList.as_view(), name='deal_list_paginator'),
    url(r'^deals/(?P<status>draft|ready|paid|ordered)/$',
        DealList.as_view(), name='deal_filtered_list'),
    url(r'^deals/(?P<status>draft|ready|paid|ordered)page/(?P<page>[0-9]+)?/$',
        DealList.as_view(), name='deal_list_filtered_paginator'),
    url(r'^deals/item/(?P<item_id>[0-9]+)/delete/$',
        DealItemDelete.as_view(), name='deal_item_delete'),
    url(r'^deals/item/(?P<item_id>[0-9]+)/$',
        DealItemDetail.as_view(), name='deal_item_detail'),
    url(r'^category/tree/(?P<b2_type>b2b|b2c)/$', category_tree_json,
        name='category_tree_json'),
    url(r'^category/tree/demo/(?P<b2_type>b2b|b2c)/$',
        category_tree_demo,
        name='category_tree_demo'),
    # Product's producers
    url(r'^producers/$',
        ProducerList.as_view(),
        name='producer_list'),
    url(r'^producers/page(?P<page>[0-9]+)?/$',
        ProducerList.as_view(),
        name='producer_list_paginator'),
    url(r'^producers/add/$',
        ProducerCreate.as_view(),
        name='producer_add'),
    url(r'^producers/update/(?P<pk>[0-9]+)/$',
        ProducerUpdate.as_view(),
        name='producer_update'),
    url(r'^producers/delete/(?P<pk>[0-9]+)/$',
        ProducerDelete.as_view(),
        name='producer_delete'),
    url(r'^extraparams/(?P<item_id>[0-9]+)/$',
        ExtraParamsList.as_view(), name='extra_params_list'),
    url(r'^extraparams/(?P<item_id>[0-9]+)/add/$',
        ExtraParamsCreate.as_view(), name='extra_params_create'),
    url(r'^extraparams/(?P<item_id>[0-9]+)/update/(?P<field_name>\w+)/$',
        ExtraParamsUpdate.as_view(), name='extra_params_update'),
    url(r'^extraparams/(?P<item_id>[0-9]+)/delete/(?P<field_name>\w+)/$',
        ExtraParamsDelete.as_view(), name='extra_params_delete'),
]
