angular.module('gettext').run(['gettextCatalog', function (gettextCatalog) {
/* jshint -W100 */
    gettextCatalog.setStrings('hy_AM', {"Arabic":"Արաբներ","Armenian":"Armenian","Ask question":"Հարց Հարց","Chinese":"Չինական","display vertical":"շիտակ","English":"Անգլերեն","Hebrew":"եբրայեցի","Main page":"տուն","Massage":"հաղորդագրություն","Russian":"ռուսական","Send":"ներկայացնել","Your email":"քո էլէկտրոնային փոստը","Your name":"ձեր անունը","Вернуться назад":"ետ","На главную":"տուն"});
    gettextCatalog.setStrings('ar', {"Arabic":"عربي","Armenian":"الأرمينية","Ask question":"اسأل سؤالا","Chinese":"صيني","display vertical":"عرض عمودي","English":"الانجليزية","Hebrew":"العبرية","Main page":"الصفحة الرئيسية","Massage":"رسالة","Russian":"الروسية","Send":"إرسال","Your email":"بريدك الالكتروني","Your name":"اسمك","Вернуться назад":"إلى الوراء","На главную":"منزل"});
    gettextCatalog.setStrings('en', {"Arabic":"Arabic","Armenian":"Armenian","Ask question":"Ask question","Chinese":"Chinese","display vertical":"display vertical","English":"English","Hebrew":"Hebrew","Main page":"Main page","Massage":"Massage","Russian":"Russian","Send":"Send","Your email":"Your email","Your name":"Your name","Вернуться назад":"Go back","На главную":"Home"});
    gettextCatalog.setStrings('he_IL', {"Arabic":"ערבית","Armenian":"ארמני","Ask question":"שאל שאלה","Chinese":"סיני","display vertical":"תצוגה אנכית","English":"אנגלית","Hebrew":"עברית","Main page":"בית","Massage":"הודעה","Russian":"רוסי","Send":"להגיש","Your email":"האימייל שלך","Your name":"השם שלך","Вернуться назад":"חזרו","На главную":"בית"});
    gettextCatalog.setStrings('ru', {"Arabic":"Арабский","Armenian":"Армянский","Ask question":"Задайте Вопрос!","Chinese":"Китайский","display vertical":"Вертикальный","Hebrew":"Иврит","Main page":"Главная страница","Massage":"Сообщение","Russian":"Русский","Send":"Отправить","Your email":"Ваш email","Your name":"Ваше имя","Вернуться назад":"Вернуться назад","На главную":"На главную"});
    gettextCatalog.setStrings('zh', {"Arabic":"阿拉伯语","Ask question":"亚美尼亚","Chinese":"中国","display vertical":"垂坠","English":"英语","Hebrew":"希伯来语","Main page":"主页","Massage":"信息","Russian":"俄","Send":"提交","Your email":"你的邮件","Your name":"你的名字","Вернуться назад":"退回","На главную":"主页"});
/* jshint +W100 */
}]);